version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "example"
      MYSQL_DATABASE: "tinode"
      MYSQL_USER: "tinode"
      MYSQL_PASSWORD: "tinode"
      MYSQL_ROOT_HOST: "%"
    networks:
      tinode-net:
        aliases:
          - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "tinode", "-ptinode"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "127.0.0.1:3306:3306"

  tinode:
    image: tinode/tinode-mysql:latest
    container_name: tinode-srv
    volumes:
      - ./logs:/var/log
      - ./tinode.conf:/opt/tinode/tinode.conf
    ports:
      - "127.0.0.1:6060:6060"
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint: []
    command: ["/bin/sh", "-c", "cd /opt/tinode && ./init-db -reset -upgrade -config=tinode.conf && ./tinode --config=tinode.conf"]
    networks:
      tinode-net:
        aliases:
          - tinode
    restart: always

networks:
  tinode-net:
    driver: bridge

volumes:
  mysql_data: 