version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      default:
        aliases:
          - mysql

  tinode:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinode-0
    hostname: tinode-0
    restart: always
    ports:
      - "6060:6060"
      - "12000:12000"
      - "12001:12001"
      - "12002:12002"
      - "12003:12003"
      - "16060:16060"
    depends_on:
      - db
    networks:
      default:
        aliases:
          - tinode.host
    labels:
      name: "TinodeChatServer"
      version: "0.22.13"
      maintainer: "Tinode Team <info@tinode.co>"

networks:
  default:
    name: tinode-compose_default 