version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "tinode"
      MYSQL_DATABASE: "tinode"
      MYSQL_USER: "tinode"
      MYSQL_PASSWORD: "tinode"
      MYSQL_ROOT_HOST: "%"
    networks:
      tinode-net:
        aliases:
          - mysql.tinode-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptinode"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  tinode:
    image: tinode/tinode:0.22.12
    container_name: tinode-srv
    volumes:
      - ./tinode.conf:/etc/tinode/tinode.conf
      - ./logs:/var/log
    ports:
      - "6060:6060"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - WAIT_FOR=mysql.tinode-net:3306
      - WAIT_TIMEOUT=60
      - MYSQL_DSN=tinode:tinode@tcp(mysql.tinode-net:3306)/tinode?parseTime=true
      - STORE_USE_ADAPTER=mysql
      - API_KEY_SALT=T713/rYYgW7g4m3vG6zGRh7+FM1t0T8j13koXScOAj4=
      - AUTH_TOKEN_KEY=wfaY2RgF2S1OQI/ZlK+LSrp1KB2jwAdGAIHQ7JZn+Kc=
      - UID_ENCRYPTION_KEY=la6YsO+bNX/+XIkOqc5Svw==
    networks:
      tinode-net:
        aliases:
          - tinode.tinode-net
    restart: always

networks:
  tinode-net:
    driver: bridge

volumes:
  mysql_data: 